// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SklepNet_MVC.Data;

#nullable disable

namespace SklepNet_MVC.Migrations
{
    [DbContext(typeof(SklepNetDBContext))]
    [Migration("20230805125955_initializeDB")]
    partial class initializeDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SklepNet_MVC.Models.CMS.Aktualnosci", b =>
                {
                    b.Property<int>("IdAktualnosc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAktualnosc"));

                    b.Property<int>("Pozycja")
                        .HasColumnType("int");

                    b.Property<string>("Tresc")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Tytul")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdAktualnosc");

                    b.ToTable("Aktualnosci");
                });

            modelBuilder.Entity("SklepNet_MVC.Models.Sklep.StanyMagazynowe", b =>
                {
                    b.Property<int>("IdStanMagazynowy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStanMagazynowy"));

                    b.Property<DateTime>("DataDodania")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTowar")
                        .HasColumnType("int");

                    b.Property<int>("Stan")
                        .HasColumnType("int");

                    b.Property<int>("TowarIdTowar")
                        .HasColumnType("int");

                    b.HasKey("IdStanMagazynowy");

                    b.HasIndex("TowarIdTowar");

                    b.ToTable("StanyMagazynowe");
                });

            modelBuilder.Entity("SklepNet_MVC.Models.Sklep.Towar", b =>
                {
                    b.Property<int>("IdTowar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTowar"));

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("VIPtowar")
                        .HasColumnType("bit");

                    b.Property<bool>("towarPromocyjny")
                        .HasColumnType("bit");

                    b.HasKey("IdTowar");

                    b.ToTable("Towar");
                });

            modelBuilder.Entity("SklepNet_MVC.Models.Sklep.TowarZdjecie", b =>
                {
                    b.Property<int>("IdTowarZdjecie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTowarZdjecie"));

                    b.Property<int>("IdTowar")
                        .HasColumnType("int");

                    b.Property<int>("TowarIdTowar")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTowarZdjecie");

                    b.HasIndex("TowarIdTowar");

                    b.ToTable("TowarZdjecie");
                });

            modelBuilder.Entity("SklepNet_MVC.Models.Sklep.StanyMagazynowe", b =>
                {
                    b.HasOne("SklepNet_MVC.Models.Sklep.Towar", "Towar")
                        .WithMany("StanyMagazynowe")
                        .HasForeignKey("TowarIdTowar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Towar");
                });

            modelBuilder.Entity("SklepNet_MVC.Models.Sklep.TowarZdjecie", b =>
                {
                    b.HasOne("SklepNet_MVC.Models.Sklep.Towar", "Towar")
                        .WithMany("TowarZdjecie")
                        .HasForeignKey("TowarIdTowar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Towar");
                });

            modelBuilder.Entity("SklepNet_MVC.Models.Sklep.Towar", b =>
                {
                    b.Navigation("StanyMagazynowe");

                    b.Navigation("TowarZdjecie");
                });
#pragma warning restore 612, 618
        }
    }
}
